package com.ryannm.android.ankimate.Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ANKI_NOTE".
 */
public class AnkiNote {

    private Long id;
    private Long configurationId;
    private String fields;
    private Long deckId;
    private String tags;
    private String notebookTitle;
    private String noteTitle;

    public AnkiNote() {
    }

    public AnkiNote(Long id) {
        this.id = id;
    }

    public AnkiNote(Long id, Long configurationId, String fields, Long deckId, String tags, String notebookTitle, String noteTitle) {
        this.id = id;
        this.configurationId = configurationId;
        this.fields = fields;
        this.deckId = deckId;
        this.tags = tags;
        this.notebookTitle = notebookTitle;
        this.noteTitle = noteTitle;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getConfigurationId() {
        return configurationId;
    }

    public void setConfigurationId(Long configurationId) {
        this.configurationId = configurationId;
    }

    public String getFields() {
        return fields;
    }

    public void setFields(String fields) {
        this.fields = fields;
    }

    public Long getDeckId() {
        return deckId;
    }

    public void setDeckId(Long deckId) {
        this.deckId = deckId;
    }

    public String getTags() {
        return tags;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }

    public String getNotebookTitle() {
        return notebookTitle;
    }

    public void setNotebookTitle(String notebookTitle) {
        this.notebookTitle = notebookTitle;
    }

    public String getNoteTitle() {
        return noteTitle;
    }

    public void setNoteTitle(String noteTitle) {
        this.noteTitle = noteTitle;
    }

}
