package com.ryannm.android.ankimate.Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BLACK_LIST".
 */
public class BlackList {

    private String id;
    private String noteTitle;
    private Integer cardsAdded;
    private String notebook;

    public BlackList() {
    }

    public BlackList(String id) {
        this.id = id;
    }

    public BlackList(String id, String noteTitle, Integer cardsAdded, String notebook) {
        this.id = id;
        this.noteTitle = noteTitle;
        this.cardsAdded = cardsAdded;
        this.notebook = notebook;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getNoteTitle() {
        return noteTitle;
    }

    public void setNoteTitle(String noteTitle) {
        this.noteTitle = noteTitle;
    }

    public Integer getCardsAdded() {
        return cardsAdded;
    }

    public void setCardsAdded(Integer cardsAdded) {
        this.cardsAdded = cardsAdded;
    }

    public String getNotebook() {
        return notebook;
    }

    public void setNotebook(String notebook) {
        this.notebook = notebook;
    }

}
