package com.ryannm.android.ankimate.Dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig configurationDaoConfig;
    private final DaoConfig blackListDaoConfig;
    private final DaoConfig ankiNoteDaoConfig;

    private final ConfigurationDao configurationDao;
    private final BlackListDao blackListDao;
    private final AnkiNoteDao ankiNoteDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        configurationDaoConfig = daoConfigMap.get(ConfigurationDao.class).clone();
        configurationDaoConfig.initIdentityScope(type);

        blackListDaoConfig = daoConfigMap.get(BlackListDao.class).clone();
        blackListDaoConfig.initIdentityScope(type);

        ankiNoteDaoConfig = daoConfigMap.get(AnkiNoteDao.class).clone();
        ankiNoteDaoConfig.initIdentityScope(type);

        configurationDao = new ConfigurationDao(configurationDaoConfig, this);
        blackListDao = new BlackListDao(blackListDaoConfig, this);
        ankiNoteDao = new AnkiNoteDao(ankiNoteDaoConfig, this);

        registerDao(Configuration.class, configurationDao);
        registerDao(BlackList.class, blackListDao);
        registerDao(AnkiNote.class, ankiNoteDao);
    }
    
    public void clear() {
        configurationDaoConfig.getIdentityScope().clear();
        blackListDaoConfig.getIdentityScope().clear();
        ankiNoteDaoConfig.getIdentityScope().clear();
    }

    public ConfigurationDao getConfigurationDao() {
        return configurationDao;
    }

    public BlackListDao getBlackListDao() {
        return blackListDao;
    }

    public AnkiNoteDao getAnkiNoteDao() {
        return ankiNoteDao;
    }

}
